name: CD
on:
  push:
    branches:
      - workflows-cd

jobs:
  deploy:
    name: Deploy Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: workflows-cd
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 60 # secs
          running-workflow-name: "deploy" # HERE
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install firebase-cli
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: echo 'SUCCESS'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
